#!/usr/bin/env bash

MSG_TAG="volume"
get_current_volume() {
  pactl list sinks | grep -P "(\t)+Volume" | grep -E "[0-9]+{1,3}%" -o | head -1 | cut -d "%" -f 1
}
get_muted_status() {
 pacmd list-sinks | awk '/muted/ { print $2 }'
}
VOLUME=$(get_current_volume)
[[ $(get_muted_status) == "yes" ]] && dunstify "volume: Muted" && exit 0
dunstify "volume: $VOLUME" -a "volume_level" -h string:x-dunst-stack-tag:$MSG_TAG -h int:value:$VOLUME

