#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
setxkbmap fr

bspc monitor -d 1 2 3 4
bspc config border_width    2
bspc config window_gap      2
bspc config top_padding     0
bspc config left_padding    0
bspc config right_padding   0
bspc config bottom_padding  0

bspc config gapless_monocle       true
bspc config borderless_monocle    false
bspc config single_monocle        true
## bspc config paddingless_monocle false

bspc config focus_follows_pointer true
bspc config split_ratio         0.5
