#!/usr/bin/env bash

SUPPORTED_OPERATIONS=("+" "-" "x")
OPERATION=$1
INCREMENT=$2
MAX=100

usage() {
  echo "volume <OPERATION> [INCREMENT]"
  echo "    OPERATION:    ${SUPPORTED_OPERATIONS[*]}"
  echo "    INCREMENT:    number (empty if OPERATION is x)"
}

[[ $# -eq 0 || ! ${SUPPORTED_OPERATIONS[*]} =~ "$OPERATION" ]] \
  && echo "operation ($OPERATION) not suppored" \
  && usage \
  && exit 1;

[[ "$OPERATION" == "+" || "$OPERATION" == "-" ]] && [[ -z $INCREMENT ]] \
  && echo "no increment supplied" \
  && usage \
  && exit 1;

get_current_volume() {
  pactl list sinks | grep -P "(\t)+Volume" | grep -E "[0-9]+{1,3}%" -o | head -1 | cut -d "%" -f 1
}

apply() {
  OPERATION=$1
  INCREMENT=$2
  CURRENT_VOLUME=$(get_current_volume)
  case $OPERATION in
    "+")
      echo "increasing volume by $INCREMENT"
      NEXT_LIMIT=$(($CURRENT_VOLUME + $INCREMENT))
      [[ $(get_current_volume) == 100 ]] && exit 0;
      [[ $NEXT_LIMIT -ge 100 ]] \
      && pactl set-sink-volume @DEFAULT_SINK@ "100%" \
      || pactl set-sink-volume @DEFAULT_SINK@ "+$INCREMENT%"
      ;;
    "-")
      echo "reducing volume by $INCREMENT"
      pactl set-sink-volume @DEFAULT_SINK@ "-$INCREMENT%"
      ;;
    "x")
      echo "toggling mute"
      pactl set-sink-mute 0 toggle
      ;;
  esac;

}

apply $OPERATION $INCREMENT

# get muted status:
#   pacmd list-sinks | awk '/muted/ { print $2 }'

