#!/usr/bin/env bash

MIN_LIMIT=20
CRITICAL_MIN_LIMIT=50

MAX_LIMIT=80
CRITICAL_MAX_LIMIT=90
CHARGING_STATUS="Charging"
DISCHARGING_STATUS="Discharging"
NOTIF_TAG="battery"
APP_NAME="battery"
NOTIF_TITLE=""
NOTIF_CONTENT=""
CHARGE=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/BAT1/status)

notify() {
  BATTERY_LEVEL=$1
  URGENCY=$2
  dunstify "Battery level: $BATTERY_LEVEL%" \
  -a $APP_NAME \
  -h string:x-dunst-stack-tag:$NOTIF_TAG \
  --urgency=$URGENCY
}

if [[ "$STATUS" == "$DISCHARGING_STATUS" ]]; then
  if [[ $CHARGE -le $CRITICAL_MIN_LIMIT ]]; then
    NOTIF_LEVEL="critical"
  elif [[ $CHARGE -le $MIN_LIMIT ]]; then
    NOTIF_LEVEL="normal"
  fi
elif [[ "$STATUS" == "$CHARGING_STATUS" ]]; then
  if [[ $CHARGE -ge $CRITICAL_MAX_LIMIT ]]; then
    NOTIF_LEVEL="critical"
  elif [[ $CHARGE -ge $MAX_LIMIT ]]; then
    NOTIF_LEVEL="normal"
  fi
fi

if [[ "$NOTIF_LEVEL" == "" ]]; then
  echo "Everything is normal"
  echo $CHARGE $STATUS
else
  notify $CHARGE $NOTIF_LEVEL
fi
