#!/usr/bin/env bash
CHARGE=$(cat /sys/class/power_supply/BAT1/capacity)
MSG_TAG="battery"
dunstify "battery: $CHARGE%" -a "battery_level" -h string:x-dunst-stack-tag:$MSG_TAG -h int:value:$(($CHARGE))
